# Config file for automatic testing at travis-ci.org
language: python
dist: xenial
virt: lxd
cache: false
os: linux

jobs:
  include:
    - env:
      stage: test
      python: '3.7'
      install:
        - pipenv install --dev --ignore-pipfile
      before_script: # code coverage tool
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
      script:
        - pytest --cov-report xml --cov-report term
      after_script:
        - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

    - env:
      stage: deploy
      python: '3.7'
      install:
        - pipenv install --dev --ignore-pipfile --deploy
      script:
        - pipenv run python submit.py

stages:
  - name: test

  - name: deploy
    if: branch = main


before_install:
  - echo -e "machine github.com\n  login $CI_USER_TOKEN" > ~/.netrc

notifications:
  email:
    on_success: never
    on_failure: always
