# Generated by Django 3.2 on 2021-04-29 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Subscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("email_hash", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("station_name", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=1)),
                ("last_email_date", models.DateTimeField()),
                ("email_preferred_time", models.CharField(max_length=1)),
                ("timezone", models.CharField(max_length=10)),
                ("created_date", models.DateTimeField()),
                ("update_date", models.DateTimeField()),
                (
                    "subscriber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="subscribe.subscriber",
                    ),
                ),
            ],
        ),
    ]
