# Generated by Django 3.2 on 2021-04-30 18:55

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscribe", "0002_auto_20210430_1808"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subscription",
            old_name="email_preferred_time",
            new_name="time_of_day",
        ),
        migrations.AlterField(
            model_name="subscriber",
            name="confirmed_date",
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name="subscriber",
            name="created_date",
            field=models.DateTimeField(default=datetime.date(2021, 4, 30)),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="created_date",
            field=models.DateTimeField(default=datetime.date(2021, 4, 30)),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="last_email_date",
            field=models.DateTimeField(default=datetime.date(2021, 4, 30)),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="update_date",
            field=models.DateTimeField(default=datetime.date(2021, 4, 30)),
        ),
    ]
