# Generated by Django 3.2 on 2021-04-30 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscribe", "0004_alter_subscription_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="subscriber",
        ),
        migrations.AddField(
            model_name="subscription",
            name="email",
            field=models.EmailField(default=None, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subscription",
            name="temp_token",
            field=models.CharField(default=None, max_length=24),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subscription",
            name="verified",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name="Subscriber",
        ),
    ]
