# Generated by Django 3.2 on 2021-04-30 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscribe", "0005_auto_20210430_1917"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="status",
            field=models.CharField(
                choices=[("A", "Active"), ("I", "Inactive")], default="A", max_length=1
            ),
        ),
    ]
