# Generated by Django 3.2 on 2021-04-30 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscribe", "0006_alter_subscription_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subscription",
            old_name="station_name",
            new_name="station",
        ),
        migrations.AlterUniqueTogether(
            name="subscription",
            unique_together={("email", "station")},
        ),
    ]
