# Generated by Django 3.2.2 on 2021-05-08 13:22

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscribe", "0008_auto_20210430_2219"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subscription",
            old_name="station",
            new_name="city",
        ),
        migrations.AlterField(
            model_name="subscription",
            name="created_date",
            field=models.DateTimeField(default=datetime.date(2021, 5, 8)),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="next_email_date",
            field=models.DateTimeField(default=datetime.date(2021, 5, 8)),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="update_date",
            field=models.DateTimeField(default=datetime.date(2021, 5, 8)),
        ),
        migrations.AlterUniqueTogether(
            name="subscription",
            unique_together={("email", "city")},
        ),
    ]
